"""empty message

Revision ID: 5352d9d0cbdd
Revises: 08c460f49ba7
Create Date: 2021-11-05 16:15:46.081820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5352d9d0cbdd'
down_revision = '08c460f49ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_genres',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    op.drop_table('book_genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_genre',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='book_genre_book_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='book_genre_genre_id_fkey'),
    sa.PrimaryKeyConstraint('book_id', 'genre_id', name='book_genre_pkey')
    )
    op.drop_table('books_genres')
    # ### end Alembic commands ###
