"""empty message

Revision ID: 933ef47c9ee5
Revises: 24c7c2657dfa
Create Date: 2021-11-03 16:07:57.837994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933ef47c9ee5'
down_revision = '24c7c2657dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###
